# gitlab-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    app: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgresql-service
spec:
  ports:
  - port: 5432
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis-service
spec:
  ports:
  - port: 6379
  selector:
    app: redis
