# gitlab-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-password
  namespace: default
type: Opaque
data:
  root-password: cGFzc3dvcmQK  # la password è "password" (quella passata in root-password è codificata in base64)
